- name: Commit and push changes
        if: success()  # Only run if previous steps succeed
        working-directory: ./tracker
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Retry loop to handle concurrent push conflicts
          for i in {1..3}; do
            git fetch origin
            git checkout main
            git pull --rebase origin main || { echo "Rebase failed, resetting and retrying"; git rebase --abort; continue; }
            
            # Stage and commit changes
            git add steam_games_db.csv
            git commit -m "Update steam_games_db.csv with latest scrape data" || { echo "No changes to commit"; exit 0; }
            
            # Attempt to push
            if git push https://x:${{ secrets.GITHUB_TOKEN }}@github.com/mawga2/personal.git HEAD:main; then
              echo "Push succeeded"
              exit 0
            else
              echo "Push failed, retrying after delay..."
              sleep 5
              git reset --hard origin/main  # Reset to latest remote state
            fi
          done
          
          echo "Error: Failed to push changes after 3 retries"
          exit 1
